### PR TITLE
Scoped authentication support? 

### PR DESCRIPTION
**Pull request by thisiscam**
I just forked into my repo an OAuth2Scoped0Authentication that provides scoped authorization on top of the original OAuth20Authentication; basically it allow us to declare requires scope for certain resource and specific http methods。
e.g.
authentication = OAuth2Scoped0Authentication(
                            post=("read write",),
                            get=("read",),
                            put=("read","write")
                        )
Don't know if the owner of this repo is interested in this pull request? 
if that is the case, it can be found here: https://github.com/thisiscam/django-tastypie-oauth/blob/master/tastypie_oauth/authentication.py#L100

I'm quite new to django/tastypie and there might be stuff that might not smell right, so that's another reason why I would like to take my code onto the table:)

### CODE REVIEW

**Comment by honestbleeps** [comment]
hi there - I'd be very interested in seeing this merged, is there a reason it's still outstanding?  Has work on django-tastypie-oauth ceased?

thanks!

**Comment by brad** [comment]
@honestbleeps I am working on this, will try to get it merge soon.

**Comment by honestbleeps** [comment]
awesome, thank you Brad! Appreciate the prompt response! have a beer on me! @changetip

**Comment by changetip** [comment]
Hi @thisiscam, @honestbleeps sent you a Bitcoin tip worth a beer (12,187 bits/$3.50), and I'm here to deliver it ➔ **[collect your tip](https://www.changetip.com/collect/643451)**.


**[Learn more about ChangeTip](https://www.changetip.com/tip-online/github)**

**Comment by honestbleeps** [comment]
a beer for @brad also, @changetip

**Comment by changetip** [comment]
Hi @brad, @honestbleeps sent you a Bitcoin tip worth a beer (12,187 bits/$3.50), and I'm here to deliver it ➔ **[collect your tip](https://www.changetip.com/collect/643453)**.


**[Learn more about ChangeTip](https://www.changetip.com/tip-online/github)**

**Comment by brad** [comment]
Thanks @honestbleeps !

**Comment by brad** [comment]
Hi @thisiscam and @honestbleeps I've merged this in with a few changes in master. I would be really grateful if you could use it and provide me with any feedback.

**Comment by honestbleeps** [comment]
testing a bit and it's working, thanks for getting this merged! I'm currently including via a -e and a direct reference to the github repo though, because otherwise I get 0.0.2 which I believe doesn't include this new change.

**Comment by brad** [comment]
Thanks for testing @honestbleeps, I've pushed 0.0.3 to PyPi now.

**Pull request merged**
